[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.12"
reed-solomon-erasure = "6.0"
rand = { version = "0.8.5" }